/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
//    kotlin("jvm") version "1.7.21"
    id("com.xsw22wsx.aoc.kotlin-common-conventions")
}

repositories {
    mavenCentral()
}

dependencies {
}

